[build-system]
requires = ["setuptools>=61.0", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pHarmony"
dynamic = ["version"]
description = "Package for matching multidimensional NMR peaks"
requires-python = ">=3.9"
dependencies = [
    "numpy>=1.24.0,<2",
    "pandas>=2.0 ",
    "torch>=2.0",
    "matplotlib>=3.2",
    "scipy>=1.10",
    "scikit-learn>=1.6.1",
    "tqdm>=4.67.1"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where=["src"]

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "node-and-date"
tag_regex = "^v(?P<version>\\d+\\.\\d+\\.\\d+)$"
root = "."
write_to = "src/pHarmony/_version.py"

[project.scripts]
pHarmony = "pHarmony.pHarmony:main"
